- name: Create installation directory
  win_file:
    path: "{{ sysmon_install_path }}"
    state: directory

- name: Check if sysmon is installed
  win_service:
    name: sysmon
  register: sysmon_installed
  ignore_errors: yes
  when: ansible_architecture == "32-bit"

- name: Check if sysmon64 is installed
  win_service:
    name: sysmon64
  register: sysmon64_installed
  ignore_errors: yes
  when: ansible_architecture == "64-bit"

- name: Check sysmon version
  win_file_version:
    path: "C:\\WINDOWS\\sysmon.exe"
  ignore_errors: True
  register: sysmon_installed_version
  when: 
    - ansible_architecture == "32-bit"
    - sysmon_installed.exists

- name: Check sysmon64 version
  win_file_version:
    path: "C:\\WINDOWS\\sysmon64.exe"
  ignore_errors: True
  register: sysmon64_installed_version
  when: 
    - ansible_architecture == "64-bit"
    - sysmon64_installed.exists

- name: DBG
  debug:
    msg: "Uninstall will be executed"
  when:
    - ansible_architecture == "64-bit"
    - sysmon64_installed.exists
    - sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<')

- name: Uninstall sysmon
  win_command: sysmon -u
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture == "32-bit"
    - sysmon_installed.exists
    - sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<')

- name: Uninstall sysmon64
  win_command: sysmon64 -u
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture == "64-bit"
    - sysmon64_installed.exists
    - sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<')

- name: Upload sysmon
  win_copy:
    src: files/Sysmon.exe
    dest: "{{ sysmon_install_path }}\\Sysmon.exe"
    force: yes
  when:
    - ansible_architecture == "32-bit"
    - not sysmon_installed.exists or sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<')

- name: Upload sysmon64
  win_copy:
    src: files/Sysmon64.exe
    dest: "{{ sysmon_install_path }}\\Sysmon64.exe"
    force: yes
  when:
    - ansible_architecture == "64-bit"
    - not sysmon64_installed.exists or sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<')

- name: Upload sysmon configuration
  win_copy:
    src: files/{{ sysmon_config }}
    dest: "{{ sysmon_install_path }}\\sysmonconfig.xml"
  notify: reload-sysmon
  when: ansible_architecture == "32-bit"
  tags: configure

- name: Upload sysmon64 configuration
  win_copy:
    src: files/{{ sysmon_config }}
    dest: "{{ sysmon_install_path }}\\sysmonconfig.xml"
  notify: reload-sysmon64
  when: ansible_architecture == "64-bit"
  tags: configure

- name: Install sysmon
  win_command: sysmon -i -accepteula
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture == "32-bit"
    - not sysmon_installed.exists or sysmon_installed_version.win_file_version.product_version is version(sysmon_version, '<')
  notify: restart-sysmon

- name: Install sysmon64
  win_command: sysmon64 -i -accepteula
  args:
    chdir: "{{ sysmon_install_path }}"
  when:
    - ansible_architecture == "64-bit"
    - not sysmon64_installed.exists or sysmon64_installed_version.win_file_version.product_version is version(sysmon_version, '<')
  notify: restart-sysmon64
