- name: restart-sysmon
  win_shell: Restart-Service sysmon

- name: restart-sysmon64
  win_shell: Restart-Service sysmon64

- name: reload-sysmon
  win_command: "{{ sysmon_install_location }}\\Sysmon.exe -c {{ sysmon_install_location }}\\sysmonconfig.xml"
  args:
    chdir: "{{ sysmon_install_location }}"

- name: reload-sysmon64
  win_command: "{{ sysmon_install_location }}\\Sysmon64.exe -c {{ sysmon_install_location }}\\sysmonconfig.xml"
  args:
    chdir: "{{ sysmon_install_location }}"
