- name: Prepare
  hosts: all
  tasks:
    - name: (Debian/Ubuntu) apt-get update
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: (REHL/Centos) yum update
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
