name: Test ansible role installation
on:
  push:
    branches:
      - "*"
      - "!master"
    pull_request:
      branches: [ master ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "ansible-role-sysmon"
      - uses: msys2/setup-msys2@v2
        with:
          update: false
          install: base-devel git gcc msys2-devel python3 python3-pip libffi libffi-devel libcrypt libcrypt-devel openssl openssl-devel
      - name: Download ConfigureRemotingForAnsible.ps1
        run: wget https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -Outfile ConfigureRemotingForAnsible.ps1
        shell: powershell
      - name: Run ConfigureRemotingForAnsible.ps1
        run: .\ConfigureRemotingForAnsible.ps1 -Verbose -GlobalHttpFirewallAccess -ForceNewSSLCert
        shell: powershell
      - name: Get WinRM configuration
        run: winrm enumerate winrm/config/Listener
        shell: powershell
      - name: Allow WinRM HTTPS on firewall
        run: New-NetFirewallRule -DisplayName "Windows Remote Management (HTTPS-In)" -Name "WINRM (HTTPS-In)" -Profile Any -LocalPort 5986 -Protocol TCP
        shell: powershell
      - name: Get firewall WinRM
        run: Get-NetFirewallRule -Name 'WINRM*' | Select-Object Name, Description
        shell: powershell
      - name: Get TrustedHosts
        run: Get-Item WSMan:\localhost\Client\TrustedHosts
        shell: powershell
      - name: Prepare Administrator user
        run: |
          $password = ConvertTo-SecureString "Password123" -AsPlainText -Force
          New-LocalUser "Ansible" -Password $password -Description "Ansible remoting user"
          Add-LocalGroupMember -Group Administrators -Member Ansible
          Enable-LocalUser -Name "Ansible"
        shell: powershell
      - name: Install Ansible
        shell: msys2 {0}
        run: CFLAGS=-I/usr/lib/libffi-3.2.1/include python -m pip install ansible pywinrm
      - name: Copy playbook to workspace
        run: cp .\ansible-role-sysmon\.github\scripts\playbook.yml $GITHUB_WORKSPACE\playbook.yml
        shell: powershell
      - name: Run Ansible playbook
        shell: msys2 {0}
        run: |
          ansible-playbook -i ansible-role-sysmon/.github/scripts/inventory ansible-role-sysmon/.github/scripts/playbook.yml -vvvv
      - name: Run test script
        run: .\ansible-role-sysmon\.github\scripts\sysmon_test.ps1
        shell: powershell


